//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int IdProveedor { get; set; }
        public string Proveedor1 { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Direccion { get; set; }
    }
}
